//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PC_Application.Cantral {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback CTSLinkSaveBatchDTOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkGenHdrDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkSecTransDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkTerTransDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkSecRejDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkTerRejDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkTransBytesDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkRelationDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkInwardDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback LinkOutWardDtOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadMappingOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCCOMPANYMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCCONSIGNEEMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCGTINMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCLABEL_DESIGNMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCLABELTYPEMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCLINEMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCLINETYPEMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCPACKINGLEVELMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCPLANTMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCPRINTERMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCPRINTMETHODMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCUSERMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCUSERROLESMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCTBLDAYOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCTBLYEAROperationCompleted;
        
        private System.Threading.SendOrPostCallback STCTBLSCANNINGMETHODOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCTBLPRNTYPEOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCTBLDEPARTMENTOperationCompleted;
        
        private System.Threading.SendOrPostCallback STCTBLCHARSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::PC_Application.Properties.Settings.Default.PC_Application_Cantral_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event CTSLinkSaveBatchDTCompletedEventHandler CTSLinkSaveBatchDTCompleted;
        
        /// <remarks/>
        public event LinkGenHdrDtCompletedEventHandler LinkGenHdrDtCompleted;
        
        /// <remarks/>
        public event LinkSecTransDtCompletedEventHandler LinkSecTransDtCompleted;
        
        /// <remarks/>
        public event LinkTerTransDtCompletedEventHandler LinkTerTransDtCompleted;
        
        /// <remarks/>
        public event LinkSecRejDtCompletedEventHandler LinkSecRejDtCompleted;
        
        /// <remarks/>
        public event LinkTerRejDtCompletedEventHandler LinkTerRejDtCompleted;
        
        /// <remarks/>
        public event LinkTransBytesDtCompletedEventHandler LinkTransBytesDtCompleted;
        
        /// <remarks/>
        public event LinkRelationDtCompletedEventHandler LinkRelationDtCompleted;
        
        /// <remarks/>
        public event LinkInwardDtCompletedEventHandler LinkInwardDtCompleted;
        
        /// <remarks/>
        public event LinkOutWardDtCompletedEventHandler LinkOutWardDtCompleted;
        
        /// <remarks/>
        public event UploadMappingCompletedEventHandler UploadMappingCompleted;
        
        /// <remarks/>
        public event STCCOMPANYMasterCompletedEventHandler STCCOMPANYMasterCompleted;
        
        /// <remarks/>
        public event STCCONSIGNEEMasterCompletedEventHandler STCCONSIGNEEMasterCompleted;
        
        /// <remarks/>
        public event STCGTINMasterCompletedEventHandler STCGTINMasterCompleted;
        
        /// <remarks/>
        public event STCLABEL_DESIGNMasterCompletedEventHandler STCLABEL_DESIGNMasterCompleted;
        
        /// <remarks/>
        public event STCLABELTYPEMasterCompletedEventHandler STCLABELTYPEMasterCompleted;
        
        /// <remarks/>
        public event STCLINEMasterCompletedEventHandler STCLINEMasterCompleted;
        
        /// <remarks/>
        public event STCLINETYPEMasterCompletedEventHandler STCLINETYPEMasterCompleted;
        
        /// <remarks/>
        public event STCPACKINGLEVELMasterCompletedEventHandler STCPACKINGLEVELMasterCompleted;
        
        /// <remarks/>
        public event STCPLANTMasterCompletedEventHandler STCPLANTMasterCompleted;
        
        /// <remarks/>
        public event STCPRINTERMasterCompletedEventHandler STCPRINTERMasterCompleted;
        
        /// <remarks/>
        public event STCPRINTMETHODMasterCompletedEventHandler STCPRINTMETHODMasterCompleted;
        
        /// <remarks/>
        public event STCUSERMasterCompletedEventHandler STCUSERMasterCompleted;
        
        /// <remarks/>
        public event STCUSERROLESMasterCompletedEventHandler STCUSERROLESMasterCompleted;
        
        /// <remarks/>
        public event STCTBLDAYCompletedEventHandler STCTBLDAYCompleted;
        
        /// <remarks/>
        public event STCTBLYEARCompletedEventHandler STCTBLYEARCompleted;
        
        /// <remarks/>
        public event STCTBLSCANNINGMETHODCompletedEventHandler STCTBLSCANNINGMETHODCompleted;
        
        /// <remarks/>
        public event STCTBLPRNTYPECompletedEventHandler STCTBLPRNTYPECompleted;
        
        /// <remarks/>
        public event STCTBLDEPARTMENTCompletedEventHandler STCTBLDEPARTMENTCompleted;
        
        /// <remarks/>
        public event STCTBLCHARSCompletedEventHandler STCTBLCHARSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CTSLinkSaveBatchDT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CTSLinkSaveBatchDT(System.Data.DataTable dt, string PLANT) {
            object[] results = this.Invoke("CTSLinkSaveBatchDT", new object[] {
                        dt,
                        PLANT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CTSLinkSaveBatchDTAsync(System.Data.DataTable dt, string PLANT) {
            this.CTSLinkSaveBatchDTAsync(dt, PLANT, null);
        }
        
        /// <remarks/>
        public void CTSLinkSaveBatchDTAsync(System.Data.DataTable dt, string PLANT, object userState) {
            if ((this.CTSLinkSaveBatchDTOperationCompleted == null)) {
                this.CTSLinkSaveBatchDTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCTSLinkSaveBatchDTOperationCompleted);
            }
            this.InvokeAsync("CTSLinkSaveBatchDT", new object[] {
                        dt,
                        PLANT}, this.CTSLinkSaveBatchDTOperationCompleted, userState);
        }
        
        private void OnCTSLinkSaveBatchDTOperationCompleted(object arg) {
            if ((this.CTSLinkSaveBatchDTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CTSLinkSaveBatchDTCompleted(this, new CTSLinkSaveBatchDTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkGenHdrDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkGenHdrDt(System.Data.DataTable dt, string PLANT) {
            object[] results = this.Invoke("LinkGenHdrDt", new object[] {
                        dt,
                        PLANT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkGenHdrDtAsync(System.Data.DataTable dt, string PLANT) {
            this.LinkGenHdrDtAsync(dt, PLANT, null);
        }
        
        /// <remarks/>
        public void LinkGenHdrDtAsync(System.Data.DataTable dt, string PLANT, object userState) {
            if ((this.LinkGenHdrDtOperationCompleted == null)) {
                this.LinkGenHdrDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkGenHdrDtOperationCompleted);
            }
            this.InvokeAsync("LinkGenHdrDt", new object[] {
                        dt,
                        PLANT}, this.LinkGenHdrDtOperationCompleted, userState);
        }
        
        private void OnLinkGenHdrDtOperationCompleted(object arg) {
            if ((this.LinkGenHdrDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkGenHdrDtCompleted(this, new LinkGenHdrDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkSecTransDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkSecTransDt(System.Data.DataTable dt, string PLANT) {
            object[] results = this.Invoke("LinkSecTransDt", new object[] {
                        dt,
                        PLANT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkSecTransDtAsync(System.Data.DataTable dt, string PLANT) {
            this.LinkSecTransDtAsync(dt, PLANT, null);
        }
        
        /// <remarks/>
        public void LinkSecTransDtAsync(System.Data.DataTable dt, string PLANT, object userState) {
            if ((this.LinkSecTransDtOperationCompleted == null)) {
                this.LinkSecTransDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkSecTransDtOperationCompleted);
            }
            this.InvokeAsync("LinkSecTransDt", new object[] {
                        dt,
                        PLANT}, this.LinkSecTransDtOperationCompleted, userState);
        }
        
        private void OnLinkSecTransDtOperationCompleted(object arg) {
            if ((this.LinkSecTransDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkSecTransDtCompleted(this, new LinkSecTransDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkTerTransDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkTerTransDt(System.Data.DataTable dt, string PLANT) {
            object[] results = this.Invoke("LinkTerTransDt", new object[] {
                        dt,
                        PLANT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkTerTransDtAsync(System.Data.DataTable dt, string PLANT) {
            this.LinkTerTransDtAsync(dt, PLANT, null);
        }
        
        /// <remarks/>
        public void LinkTerTransDtAsync(System.Data.DataTable dt, string PLANT, object userState) {
            if ((this.LinkTerTransDtOperationCompleted == null)) {
                this.LinkTerTransDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkTerTransDtOperationCompleted);
            }
            this.InvokeAsync("LinkTerTransDt", new object[] {
                        dt,
                        PLANT}, this.LinkTerTransDtOperationCompleted, userState);
        }
        
        private void OnLinkTerTransDtOperationCompleted(object arg) {
            if ((this.LinkTerTransDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkTerTransDtCompleted(this, new LinkTerTransDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkSecRejDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkSecRejDt(System.Data.DataTable dt) {
            object[] results = this.Invoke("LinkSecRejDt", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkSecRejDtAsync(System.Data.DataTable dt) {
            this.LinkSecRejDtAsync(dt, null);
        }
        
        /// <remarks/>
        public void LinkSecRejDtAsync(System.Data.DataTable dt, object userState) {
            if ((this.LinkSecRejDtOperationCompleted == null)) {
                this.LinkSecRejDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkSecRejDtOperationCompleted);
            }
            this.InvokeAsync("LinkSecRejDt", new object[] {
                        dt}, this.LinkSecRejDtOperationCompleted, userState);
        }
        
        private void OnLinkSecRejDtOperationCompleted(object arg) {
            if ((this.LinkSecRejDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkSecRejDtCompleted(this, new LinkSecRejDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkTerRejDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkTerRejDt(System.Data.DataTable dt) {
            object[] results = this.Invoke("LinkTerRejDt", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkTerRejDtAsync(System.Data.DataTable dt) {
            this.LinkTerRejDtAsync(dt, null);
        }
        
        /// <remarks/>
        public void LinkTerRejDtAsync(System.Data.DataTable dt, object userState) {
            if ((this.LinkTerRejDtOperationCompleted == null)) {
                this.LinkTerRejDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkTerRejDtOperationCompleted);
            }
            this.InvokeAsync("LinkTerRejDt", new object[] {
                        dt}, this.LinkTerRejDtOperationCompleted, userState);
        }
        
        private void OnLinkTerRejDtOperationCompleted(object arg) {
            if ((this.LinkTerRejDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkTerRejDtCompleted(this, new LinkTerRejDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkTransBytesDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkTransBytesDt([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] sData, string strBatch, string strPlant, string strUsername, string strBCIL, string strPacking) {
            object[] results = this.Invoke("LinkTransBytesDt", new object[] {
                        sData,
                        strBatch,
                        strPlant,
                        strUsername,
                        strBCIL,
                        strPacking});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkTransBytesDtAsync(byte[] sData, string strBatch, string strPlant, string strUsername, string strBCIL, string strPacking) {
            this.LinkTransBytesDtAsync(sData, strBatch, strPlant, strUsername, strBCIL, strPacking, null);
        }
        
        /// <remarks/>
        public void LinkTransBytesDtAsync(byte[] sData, string strBatch, string strPlant, string strUsername, string strBCIL, string strPacking, object userState) {
            if ((this.LinkTransBytesDtOperationCompleted == null)) {
                this.LinkTransBytesDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkTransBytesDtOperationCompleted);
            }
            this.InvokeAsync("LinkTransBytesDt", new object[] {
                        sData,
                        strBatch,
                        strPlant,
                        strUsername,
                        strBCIL,
                        strPacking}, this.LinkTransBytesDtOperationCompleted, userState);
        }
        
        private void OnLinkTransBytesDtOperationCompleted(object arg) {
            if ((this.LinkTransBytesDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkTransBytesDtCompleted(this, new LinkTransBytesDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkRelationDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkRelationDt(System.Data.DataTable dt, string PLANT) {
            object[] results = this.Invoke("LinkRelationDt", new object[] {
                        dt,
                        PLANT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkRelationDtAsync(System.Data.DataTable dt, string PLANT) {
            this.LinkRelationDtAsync(dt, PLANT, null);
        }
        
        /// <remarks/>
        public void LinkRelationDtAsync(System.Data.DataTable dt, string PLANT, object userState) {
            if ((this.LinkRelationDtOperationCompleted == null)) {
                this.LinkRelationDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkRelationDtOperationCompleted);
            }
            this.InvokeAsync("LinkRelationDt", new object[] {
                        dt,
                        PLANT}, this.LinkRelationDtOperationCompleted, userState);
        }
        
        private void OnLinkRelationDtOperationCompleted(object arg) {
            if ((this.LinkRelationDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkRelationDtCompleted(this, new LinkRelationDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkInwardDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkInwardDt(System.Data.DataTable dt, string PLANT) {
            object[] results = this.Invoke("LinkInwardDt", new object[] {
                        dt,
                        PLANT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkInwardDtAsync(System.Data.DataTable dt, string PLANT) {
            this.LinkInwardDtAsync(dt, PLANT, null);
        }
        
        /// <remarks/>
        public void LinkInwardDtAsync(System.Data.DataTable dt, string PLANT, object userState) {
            if ((this.LinkInwardDtOperationCompleted == null)) {
                this.LinkInwardDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkInwardDtOperationCompleted);
            }
            this.InvokeAsync("LinkInwardDt", new object[] {
                        dt,
                        PLANT}, this.LinkInwardDtOperationCompleted, userState);
        }
        
        private void OnLinkInwardDtOperationCompleted(object arg) {
            if ((this.LinkInwardDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkInwardDtCompleted(this, new LinkInwardDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LinkOutWardDt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LinkOutWardDt(System.Data.DataTable dt, string PLANT) {
            object[] results = this.Invoke("LinkOutWardDt", new object[] {
                        dt,
                        PLANT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LinkOutWardDtAsync(System.Data.DataTable dt, string PLANT) {
            this.LinkOutWardDtAsync(dt, PLANT, null);
        }
        
        /// <remarks/>
        public void LinkOutWardDtAsync(System.Data.DataTable dt, string PLANT, object userState) {
            if ((this.LinkOutWardDtOperationCompleted == null)) {
                this.LinkOutWardDtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLinkOutWardDtOperationCompleted);
            }
            this.InvokeAsync("LinkOutWardDt", new object[] {
                        dt,
                        PLANT}, this.LinkOutWardDtOperationCompleted, userState);
        }
        
        private void OnLinkOutWardDtOperationCompleted(object arg) {
            if ((this.LinkOutWardDtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LinkOutWardDtCompleted(this, new LinkOutWardDtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadMapping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadMapping(System.Data.DataTable dt) {
            object[] results = this.Invoke("UploadMapping", new object[] {
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadMappingAsync(System.Data.DataTable dt) {
            this.UploadMappingAsync(dt, null);
        }
        
        /// <remarks/>
        public void UploadMappingAsync(System.Data.DataTable dt, object userState) {
            if ((this.UploadMappingOperationCompleted == null)) {
                this.UploadMappingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadMappingOperationCompleted);
            }
            this.InvokeAsync("UploadMapping", new object[] {
                        dt}, this.UploadMappingOperationCompleted, userState);
        }
        
        private void OnUploadMappingOperationCompleted(object arg) {
            if ((this.UploadMappingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadMappingCompleted(this, new UploadMappingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCCOMPANYMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCCOMPANYMaster(string strPlant) {
            object[] results = this.Invoke("STCCOMPANYMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCCOMPANYMasterAsync(string strPlant) {
            this.STCCOMPANYMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCCOMPANYMasterAsync(string strPlant, object userState) {
            if ((this.STCCOMPANYMasterOperationCompleted == null)) {
                this.STCCOMPANYMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCCOMPANYMasterOperationCompleted);
            }
            this.InvokeAsync("STCCOMPANYMaster", new object[] {
                        strPlant}, this.STCCOMPANYMasterOperationCompleted, userState);
        }
        
        private void OnSTCCOMPANYMasterOperationCompleted(object arg) {
            if ((this.STCCOMPANYMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCCOMPANYMasterCompleted(this, new STCCOMPANYMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCCONSIGNEEMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCCONSIGNEEMaster(string strPlant) {
            object[] results = this.Invoke("STCCONSIGNEEMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCCONSIGNEEMasterAsync(string strPlant) {
            this.STCCONSIGNEEMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCCONSIGNEEMasterAsync(string strPlant, object userState) {
            if ((this.STCCONSIGNEEMasterOperationCompleted == null)) {
                this.STCCONSIGNEEMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCCONSIGNEEMasterOperationCompleted);
            }
            this.InvokeAsync("STCCONSIGNEEMaster", new object[] {
                        strPlant}, this.STCCONSIGNEEMasterOperationCompleted, userState);
        }
        
        private void OnSTCCONSIGNEEMasterOperationCompleted(object arg) {
            if ((this.STCCONSIGNEEMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCCONSIGNEEMasterCompleted(this, new STCCONSIGNEEMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCGTINMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCGTINMaster(string strPlant) {
            object[] results = this.Invoke("STCGTINMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCGTINMasterAsync(string strPlant) {
            this.STCGTINMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCGTINMasterAsync(string strPlant, object userState) {
            if ((this.STCGTINMasterOperationCompleted == null)) {
                this.STCGTINMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCGTINMasterOperationCompleted);
            }
            this.InvokeAsync("STCGTINMaster", new object[] {
                        strPlant}, this.STCGTINMasterOperationCompleted, userState);
        }
        
        private void OnSTCGTINMasterOperationCompleted(object arg) {
            if ((this.STCGTINMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCGTINMasterCompleted(this, new STCGTINMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCLABEL_DESIGNMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCLABEL_DESIGNMaster(string strPlant) {
            object[] results = this.Invoke("STCLABEL_DESIGNMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCLABEL_DESIGNMasterAsync(string strPlant) {
            this.STCLABEL_DESIGNMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCLABEL_DESIGNMasterAsync(string strPlant, object userState) {
            if ((this.STCLABEL_DESIGNMasterOperationCompleted == null)) {
                this.STCLABEL_DESIGNMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCLABEL_DESIGNMasterOperationCompleted);
            }
            this.InvokeAsync("STCLABEL_DESIGNMaster", new object[] {
                        strPlant}, this.STCLABEL_DESIGNMasterOperationCompleted, userState);
        }
        
        private void OnSTCLABEL_DESIGNMasterOperationCompleted(object arg) {
            if ((this.STCLABEL_DESIGNMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCLABEL_DESIGNMasterCompleted(this, new STCLABEL_DESIGNMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCLABELTYPEMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCLABELTYPEMaster(string strPlant) {
            object[] results = this.Invoke("STCLABELTYPEMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCLABELTYPEMasterAsync(string strPlant) {
            this.STCLABELTYPEMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCLABELTYPEMasterAsync(string strPlant, object userState) {
            if ((this.STCLABELTYPEMasterOperationCompleted == null)) {
                this.STCLABELTYPEMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCLABELTYPEMasterOperationCompleted);
            }
            this.InvokeAsync("STCLABELTYPEMaster", new object[] {
                        strPlant}, this.STCLABELTYPEMasterOperationCompleted, userState);
        }
        
        private void OnSTCLABELTYPEMasterOperationCompleted(object arg) {
            if ((this.STCLABELTYPEMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCLABELTYPEMasterCompleted(this, new STCLABELTYPEMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCLINEMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCLINEMaster(string strPlant) {
            object[] results = this.Invoke("STCLINEMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCLINEMasterAsync(string strPlant) {
            this.STCLINEMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCLINEMasterAsync(string strPlant, object userState) {
            if ((this.STCLINEMasterOperationCompleted == null)) {
                this.STCLINEMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCLINEMasterOperationCompleted);
            }
            this.InvokeAsync("STCLINEMaster", new object[] {
                        strPlant}, this.STCLINEMasterOperationCompleted, userState);
        }
        
        private void OnSTCLINEMasterOperationCompleted(object arg) {
            if ((this.STCLINEMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCLINEMasterCompleted(this, new STCLINEMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCLINETYPEMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCLINETYPEMaster(string strPlant) {
            object[] results = this.Invoke("STCLINETYPEMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCLINETYPEMasterAsync(string strPlant) {
            this.STCLINETYPEMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCLINETYPEMasterAsync(string strPlant, object userState) {
            if ((this.STCLINETYPEMasterOperationCompleted == null)) {
                this.STCLINETYPEMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCLINETYPEMasterOperationCompleted);
            }
            this.InvokeAsync("STCLINETYPEMaster", new object[] {
                        strPlant}, this.STCLINETYPEMasterOperationCompleted, userState);
        }
        
        private void OnSTCLINETYPEMasterOperationCompleted(object arg) {
            if ((this.STCLINETYPEMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCLINETYPEMasterCompleted(this, new STCLINETYPEMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCPACKINGLEVELMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCPACKINGLEVELMaster(string strPlant) {
            object[] results = this.Invoke("STCPACKINGLEVELMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCPACKINGLEVELMasterAsync(string strPlant) {
            this.STCPACKINGLEVELMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCPACKINGLEVELMasterAsync(string strPlant, object userState) {
            if ((this.STCPACKINGLEVELMasterOperationCompleted == null)) {
                this.STCPACKINGLEVELMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCPACKINGLEVELMasterOperationCompleted);
            }
            this.InvokeAsync("STCPACKINGLEVELMaster", new object[] {
                        strPlant}, this.STCPACKINGLEVELMasterOperationCompleted, userState);
        }
        
        private void OnSTCPACKINGLEVELMasterOperationCompleted(object arg) {
            if ((this.STCPACKINGLEVELMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCPACKINGLEVELMasterCompleted(this, new STCPACKINGLEVELMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCPLANTMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCPLANTMaster(string strPlant) {
            object[] results = this.Invoke("STCPLANTMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCPLANTMasterAsync(string strPlant) {
            this.STCPLANTMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCPLANTMasterAsync(string strPlant, object userState) {
            if ((this.STCPLANTMasterOperationCompleted == null)) {
                this.STCPLANTMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCPLANTMasterOperationCompleted);
            }
            this.InvokeAsync("STCPLANTMaster", new object[] {
                        strPlant}, this.STCPLANTMasterOperationCompleted, userState);
        }
        
        private void OnSTCPLANTMasterOperationCompleted(object arg) {
            if ((this.STCPLANTMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCPLANTMasterCompleted(this, new STCPLANTMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCPRINTERMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCPRINTERMaster(string strPlant) {
            object[] results = this.Invoke("STCPRINTERMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCPRINTERMasterAsync(string strPlant) {
            this.STCPRINTERMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCPRINTERMasterAsync(string strPlant, object userState) {
            if ((this.STCPRINTERMasterOperationCompleted == null)) {
                this.STCPRINTERMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCPRINTERMasterOperationCompleted);
            }
            this.InvokeAsync("STCPRINTERMaster", new object[] {
                        strPlant}, this.STCPRINTERMasterOperationCompleted, userState);
        }
        
        private void OnSTCPRINTERMasterOperationCompleted(object arg) {
            if ((this.STCPRINTERMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCPRINTERMasterCompleted(this, new STCPRINTERMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCPRINTMETHODMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCPRINTMETHODMaster(string strPlant) {
            object[] results = this.Invoke("STCPRINTMETHODMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCPRINTMETHODMasterAsync(string strPlant) {
            this.STCPRINTMETHODMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCPRINTMETHODMasterAsync(string strPlant, object userState) {
            if ((this.STCPRINTMETHODMasterOperationCompleted == null)) {
                this.STCPRINTMETHODMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCPRINTMETHODMasterOperationCompleted);
            }
            this.InvokeAsync("STCPRINTMETHODMaster", new object[] {
                        strPlant}, this.STCPRINTMETHODMasterOperationCompleted, userState);
        }
        
        private void OnSTCPRINTMETHODMasterOperationCompleted(object arg) {
            if ((this.STCPRINTMETHODMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCPRINTMETHODMasterCompleted(this, new STCPRINTMETHODMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCUSERMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCUSERMaster(string strPlant) {
            object[] results = this.Invoke("STCUSERMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCUSERMasterAsync(string strPlant) {
            this.STCUSERMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCUSERMasterAsync(string strPlant, object userState) {
            if ((this.STCUSERMasterOperationCompleted == null)) {
                this.STCUSERMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCUSERMasterOperationCompleted);
            }
            this.InvokeAsync("STCUSERMaster", new object[] {
                        strPlant}, this.STCUSERMasterOperationCompleted, userState);
        }
        
        private void OnSTCUSERMasterOperationCompleted(object arg) {
            if ((this.STCUSERMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCUSERMasterCompleted(this, new STCUSERMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCUSERROLESMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCUSERROLESMaster(string strPlant) {
            object[] results = this.Invoke("STCUSERROLESMaster", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCUSERROLESMasterAsync(string strPlant) {
            this.STCUSERROLESMasterAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCUSERROLESMasterAsync(string strPlant, object userState) {
            if ((this.STCUSERROLESMasterOperationCompleted == null)) {
                this.STCUSERROLESMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCUSERROLESMasterOperationCompleted);
            }
            this.InvokeAsync("STCUSERROLESMaster", new object[] {
                        strPlant}, this.STCUSERROLESMasterOperationCompleted, userState);
        }
        
        private void OnSTCUSERROLESMasterOperationCompleted(object arg) {
            if ((this.STCUSERROLESMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCUSERROLESMasterCompleted(this, new STCUSERROLESMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCTBLDAY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCTBLDAY(string strPlant) {
            object[] results = this.Invoke("STCTBLDAY", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCTBLDAYAsync(string strPlant) {
            this.STCTBLDAYAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCTBLDAYAsync(string strPlant, object userState) {
            if ((this.STCTBLDAYOperationCompleted == null)) {
                this.STCTBLDAYOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCTBLDAYOperationCompleted);
            }
            this.InvokeAsync("STCTBLDAY", new object[] {
                        strPlant}, this.STCTBLDAYOperationCompleted, userState);
        }
        
        private void OnSTCTBLDAYOperationCompleted(object arg) {
            if ((this.STCTBLDAYCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCTBLDAYCompleted(this, new STCTBLDAYCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCTBLYEAR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCTBLYEAR(string strPlant) {
            object[] results = this.Invoke("STCTBLYEAR", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCTBLYEARAsync(string strPlant) {
            this.STCTBLYEARAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCTBLYEARAsync(string strPlant, object userState) {
            if ((this.STCTBLYEAROperationCompleted == null)) {
                this.STCTBLYEAROperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCTBLYEAROperationCompleted);
            }
            this.InvokeAsync("STCTBLYEAR", new object[] {
                        strPlant}, this.STCTBLYEAROperationCompleted, userState);
        }
        
        private void OnSTCTBLYEAROperationCompleted(object arg) {
            if ((this.STCTBLYEARCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCTBLYEARCompleted(this, new STCTBLYEARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCTBLSCANNINGMETHOD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCTBLSCANNINGMETHOD(string strPlant) {
            object[] results = this.Invoke("STCTBLSCANNINGMETHOD", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCTBLSCANNINGMETHODAsync(string strPlant) {
            this.STCTBLSCANNINGMETHODAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCTBLSCANNINGMETHODAsync(string strPlant, object userState) {
            if ((this.STCTBLSCANNINGMETHODOperationCompleted == null)) {
                this.STCTBLSCANNINGMETHODOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCTBLSCANNINGMETHODOperationCompleted);
            }
            this.InvokeAsync("STCTBLSCANNINGMETHOD", new object[] {
                        strPlant}, this.STCTBLSCANNINGMETHODOperationCompleted, userState);
        }
        
        private void OnSTCTBLSCANNINGMETHODOperationCompleted(object arg) {
            if ((this.STCTBLSCANNINGMETHODCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCTBLSCANNINGMETHODCompleted(this, new STCTBLSCANNINGMETHODCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCTBLPRNTYPE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCTBLPRNTYPE(string strPlant) {
            object[] results = this.Invoke("STCTBLPRNTYPE", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCTBLPRNTYPEAsync(string strPlant) {
            this.STCTBLPRNTYPEAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCTBLPRNTYPEAsync(string strPlant, object userState) {
            if ((this.STCTBLPRNTYPEOperationCompleted == null)) {
                this.STCTBLPRNTYPEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCTBLPRNTYPEOperationCompleted);
            }
            this.InvokeAsync("STCTBLPRNTYPE", new object[] {
                        strPlant}, this.STCTBLPRNTYPEOperationCompleted, userState);
        }
        
        private void OnSTCTBLPRNTYPEOperationCompleted(object arg) {
            if ((this.STCTBLPRNTYPECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCTBLPRNTYPECompleted(this, new STCTBLPRNTYPECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCTBLDEPARTMENT", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCTBLDEPARTMENT(string strPlant) {
            object[] results = this.Invoke("STCTBLDEPARTMENT", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCTBLDEPARTMENTAsync(string strPlant) {
            this.STCTBLDEPARTMENTAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCTBLDEPARTMENTAsync(string strPlant, object userState) {
            if ((this.STCTBLDEPARTMENTOperationCompleted == null)) {
                this.STCTBLDEPARTMENTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCTBLDEPARTMENTOperationCompleted);
            }
            this.InvokeAsync("STCTBLDEPARTMENT", new object[] {
                        strPlant}, this.STCTBLDEPARTMENTOperationCompleted, userState);
        }
        
        private void OnSTCTBLDEPARTMENTOperationCompleted(object arg) {
            if ((this.STCTBLDEPARTMENTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCTBLDEPARTMENTCompleted(this, new STCTBLDEPARTMENTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/STCTBLCHARS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable STCTBLCHARS(string strPlant) {
            object[] results = this.Invoke("STCTBLCHARS", new object[] {
                        strPlant});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void STCTBLCHARSAsync(string strPlant) {
            this.STCTBLCHARSAsync(strPlant, null);
        }
        
        /// <remarks/>
        public void STCTBLCHARSAsync(string strPlant, object userState) {
            if ((this.STCTBLCHARSOperationCompleted == null)) {
                this.STCTBLCHARSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTCTBLCHARSOperationCompleted);
            }
            this.InvokeAsync("STCTBLCHARS", new object[] {
                        strPlant}, this.STCTBLCHARSOperationCompleted, userState);
        }
        
        private void OnSTCTBLCHARSOperationCompleted(object arg) {
            if ((this.STCTBLCHARSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.STCTBLCHARSCompleted(this, new STCTBLCHARSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CTSLinkSaveBatchDTCompletedEventHandler(object sender, CTSLinkSaveBatchDTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CTSLinkSaveBatchDTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CTSLinkSaveBatchDTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkGenHdrDtCompletedEventHandler(object sender, LinkGenHdrDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkGenHdrDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkGenHdrDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkSecTransDtCompletedEventHandler(object sender, LinkSecTransDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkSecTransDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkSecTransDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkTerTransDtCompletedEventHandler(object sender, LinkTerTransDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkTerTransDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkTerTransDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkSecRejDtCompletedEventHandler(object sender, LinkSecRejDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkSecRejDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkSecRejDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkTerRejDtCompletedEventHandler(object sender, LinkTerRejDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkTerRejDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkTerRejDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkTransBytesDtCompletedEventHandler(object sender, LinkTransBytesDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkTransBytesDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkTransBytesDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkRelationDtCompletedEventHandler(object sender, LinkRelationDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkRelationDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkRelationDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkInwardDtCompletedEventHandler(object sender, LinkInwardDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkInwardDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkInwardDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LinkOutWardDtCompletedEventHandler(object sender, LinkOutWardDtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkOutWardDtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LinkOutWardDtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UploadMappingCompletedEventHandler(object sender, UploadMappingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadMappingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadMappingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCCOMPANYMasterCompletedEventHandler(object sender, STCCOMPANYMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCCOMPANYMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCCOMPANYMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCCONSIGNEEMasterCompletedEventHandler(object sender, STCCONSIGNEEMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCCONSIGNEEMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCCONSIGNEEMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCGTINMasterCompletedEventHandler(object sender, STCGTINMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCGTINMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCGTINMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCLABEL_DESIGNMasterCompletedEventHandler(object sender, STCLABEL_DESIGNMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCLABEL_DESIGNMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCLABEL_DESIGNMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCLABELTYPEMasterCompletedEventHandler(object sender, STCLABELTYPEMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCLABELTYPEMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCLABELTYPEMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCLINEMasterCompletedEventHandler(object sender, STCLINEMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCLINEMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCLINEMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCLINETYPEMasterCompletedEventHandler(object sender, STCLINETYPEMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCLINETYPEMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCLINETYPEMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCPACKINGLEVELMasterCompletedEventHandler(object sender, STCPACKINGLEVELMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCPACKINGLEVELMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCPACKINGLEVELMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCPLANTMasterCompletedEventHandler(object sender, STCPLANTMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCPLANTMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCPLANTMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCPRINTERMasterCompletedEventHandler(object sender, STCPRINTERMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCPRINTERMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCPRINTERMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCPRINTMETHODMasterCompletedEventHandler(object sender, STCPRINTMETHODMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCPRINTMETHODMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCPRINTMETHODMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCUSERMasterCompletedEventHandler(object sender, STCUSERMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCUSERMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCUSERMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCUSERROLESMasterCompletedEventHandler(object sender, STCUSERROLESMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCUSERROLESMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCUSERROLESMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCTBLDAYCompletedEventHandler(object sender, STCTBLDAYCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCTBLDAYCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCTBLDAYCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCTBLYEARCompletedEventHandler(object sender, STCTBLYEARCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCTBLYEARCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCTBLYEARCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCTBLSCANNINGMETHODCompletedEventHandler(object sender, STCTBLSCANNINGMETHODCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCTBLSCANNINGMETHODCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCTBLSCANNINGMETHODCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCTBLPRNTYPECompletedEventHandler(object sender, STCTBLPRNTYPECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCTBLPRNTYPECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCTBLPRNTYPECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCTBLDEPARTMENTCompletedEventHandler(object sender, STCTBLDEPARTMENTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCTBLDEPARTMENTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCTBLDEPARTMENTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void STCTBLCHARSCompletedEventHandler(object sender, STCTBLCHARSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class STCTBLCHARSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal STCTBLCHARSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591